# Generated by Django 5.1.2 on 2024-10-26 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_client_owner_mailingsettings_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingsettings",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="TryMailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_try",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата последней попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "success"), ("failure", "failure")],
                        default="success",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "response",
                    models.TextField(blank=True, null=True, verbose_name="Ответ"),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="mailings.mailingsettings",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
                "ordering": ("status",),
            },
        ),
    ]
