# Generated by Django 5.1.2 on 2024-11-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_mailingsettings_is_active_trymailing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ("FIO",),
                "permissions": [
                    ("can_view_clients", "Может смотреть просматривать клиентов"),
                    ("can_change_clients", "Может смотреть изменять клиентов"),
                    ("can_delete_clients", "Может удалять Клиентов"),
                ],
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingsettings",
            options={
                "permissions": [("change_status", "Может менять состояние рассылки")],
                "verbose_name": "настройки рассылки",
                "verbose_name_plural": "настройки рассылки",
            },
        ),
    ]
